### ISSUE TITLE
"includes folder not found"

### ISSUE THREAD

**Issue by Kevinwochan** [LarsSchy/SMAC-M#21]
Hi Team,
Running the basic map service commands i get the following error
```
cd chart-installation/generate_map_files/scripts
python3 ./generate_map_config.py -rules ../resources/layer_rules/rules/ -basechartdata /home/user/SMAC-M/ENC_ROOT
cd: no such file or directory: chart-installation/generate_map_files/scripts
Existing color tables found at /home/user/SMAC-M/chart-installation/generate_map_files/resources/layer_rules/rules/color_tables
Existing layers found in /home/user/SMAC-M/chart-installation/generate_map_files/resources/layer_rules/rules/layer_rules
Traceback (most recent call last):
  File "./generate_map_config.py", line 160, in <module>
    main()
  File "./generate_map_config.py", line 141, in main
    args.force_overwrite, args.debug, point_table, area_table, displaycategory, chartsymbols)
  File "/home/user/SMAC-M/chart-installation/generate_map_files/scripts/basechart.py", line 118, in generate_basechart_config
    map_path, fonts_path, debug, shapepath)
  File "/home/user/SMAC-M/chart-installation/generate_map_files/scripts/basechart.py", line 67, in create_capability_files
    d = get_dictionary(theme, map_path, fonts_path, debug_string)
  File "/home/user/SMAC-M/chart-installation/generate_map_files/scripts/basechart.py", line 45, in get_dictionary
    theme),
  File "/home/user/SMAC-M/chart-installation/generate_map_files/scripts/basechart.py", line 24, in generate_includes
    includes_dir) if inc.startswith(theme)]
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/SMAC-M/ENC_ROOT/map/includes'
```
I've tried creating the folder but after running the above command, the folder is deleted.

**Comment by MarekBak** [comment]
Hello Kevinwochan,
Can you rerun command from base directory (without cd command) like in example:
`python3 chart-installation/generate_map_files/generate_map_config.py ...`
Of course with all relative paths adjusted.

**Comment by Kevinwochan** [comment]
```
python3 chart-installation/generate_map_files/generate_map_config.py configfile.toml 
Existing color tables found at /home/SMAC-M/chart-installation/generate_map_files/resources/rules/color_tables
Existing layers found in /home/SMAC-M/chart-installation/generate_map_files/resources/rules/layer_rules
/home/SMAC-M/chart-installation/generate_map_files/mapgen/symbol.py:412: UserWarning: Pattern command not implemented: CI
  warnings.warn('Pattern command not implemented: ' + command)
Check geometry of all layers...
Loading DUSK.csv
Loading DAY_BRIGHT.csv
Loading DAY_WHITEBACK.csv
Loading NIGHT.csv
Loading DAY_BLACKBACK.csv
Traceback (most recent call last):
  File "chart-installation/generate_map_files/generate_map_config.py", line 151, in <module>
    displaycategory, chartsymbols)
  File "/home/SMAC-M/chart-installation/generate_map_files/mapgen/basechart.py", line 108, in generate_basechart_config
    map_path, fonts_path, debug, shapepath)
  File "/home/SMAC-M/chart-installation/generate_map_files/mapgen/basechart.py", line 62, in create_capability_files
    d = get_dictionary(theme, map_path, fonts_path, debug_string)
  File "/home/SMAC-M/chart-installation/generate_map_files/mapgen/basechart.py", line 40, in get_dictionary
    theme),
  File "/home/SMAC-M/chart-installation/generate_map_files/mapgen/basechart.py", line 19, in generate_includes
    includes_dir) if inc.startswith(theme)]
FileNotFoundError: [Errno 2] No such file or directory: '/home/SMAC-M/data/map/includes'
```

**Comment by MarekBak** [comment]
Can you dump contents of configfile.toml, please?

**Comment by Kevinwochan** [comment]
```
debug = false
displaycategory = "Standard"
area_table = "Plain"
point_table = "Paper"

[paths]
map = "/home/SMAC-M/data/map"
chartsymbols = "/home/SMAC-M/chart-installation/generate_map_files/resources/chartsymbols/chartsymbols_S57.xml"
chart = "/home/SMAC-M/ENC_ROOT"
data = "/home/SMAC-M/data/shape"
ruleset = ""
```

**Comment by MarekBak** [comment]
Can you post output from:
ls -lR /home/SMAC-M/data/shape, please?
Also what is the output of:
ogrinfo --config S57_PROFILE iw -ro <any_s57_input_file>

**Comment by Kevinwochan** [comment]
```
 ogrinfo --config S57_PROFILE iw -ro AU130120.000 
INFO: Open of `AU130120.000'
      using driver `S57' successful.
1: DSID (None)
2: Point (Point)
3: Line (Line String)
4: Area (Polygon)
5: Meta (None)
```
Drivers seem to be fine

and the folder is empty
```
/home/SMAC-M/data/shape:
total 0
```

**Comment by MarekBak** [comment]
It is not fine. Did you follow the step (your gdal path can be different):
```
$ ogrinfo --version
GDAL 2.2.2, released ...
$ find / -name s57objectclasses_iw.csv
/usr/share/gdal/2.2/s57objectclasses_iw.csv

$ wget https://raw.githubusercontent.com/OpenCPN/OpenCPN/master/data/s57data/s57objectclasses.csv
$ wget https://raw.githubusercontent.com/OpenCPN/OpenCPN/master/data/s57data/s57attributes.csv
$ cp s57objectclasses.csv /usr/share/gdal/2.2/s57objectclasses_iw.csv
$ cp s57attributes.csv /usr/share/gdal/2.2/s57attributes_iw.csv
```
