### ISSUE TITLE
Fail to run sample

### ISSUE THREAD

**Issue by fulup-bzh** [LarsSchy/SMAC-M#30]
I'm trying to run your code and fail on hopefully simple errors. I'm running on Fedora-34.

## shape files generation somehow works 

Shape files are generated but command fail on the sql part. May me something missing from my input chart ? (SHOM chart from the Morbihan golf in south Britanny)
```
+ ogr2ogr -sql 'SELECT CL5_LIGHTS_POINT.VALNMR as VALNMR,  CL5_LIGHTS_POINT.LITCHR as LITCHR, CL5_LIGHTS_POINT.SIGGRP as SIGGRP, cast(CL5_LIGHTS_POINT.SIGPER as numeric(4,1)) as SIGPER, cast(CL5_LIGHTS_POINT.HEIGHT as numeric(30,5))  as HEIGHT, CL5_LIGHTS_POINT.COLOUR as COLOUR, CL5_LIGHTS_POINT.EXCLIT as EXCLIT,litchr_code.Meaning as Meaning,colour_code.Colour_code as Colour_cod FROM '\''/home/fulup/Workspace/Linux-Marine/SMAC-M/shp_s57data/shp/5/CL5_LIGHTS_POINT.shp'\''.CL5_LIGHTS_POINT LEFT JOIN '\''litchr_code.csv'\''.litchr_code litchr_code ON CL5_LIGHTS_POINT.LITCHR = litchr_code.ID LEFT JOIN  '\''colour_code.csv'\''.colour_code colour_code ON CL5_LIGHTS_POINT.COLOUR = colour_code.ID' /home/fulup/Workspace/Linux-Marine/SMAC-M/shp_s57data/shp/5/CL5_LIGHTS_POINT_SIGNATURE.shp /home/fulup/Workspace/Linux-Marine/SMAC-M/shp_s57data/shp/5/CL5_LIGHTS_POINT.shp

>> ERROR
ERROR 1: Unrecognized field name CL5_LIGHTS_POINT.COLOUR.
```

## Map file generation fail for a missing file. 
This may come from a simple documentation error. I found the file in a different directory but a copy just move the error a little further.
```
python3 chart-installation/generate_map_files/generate_map_config.py configfile.toml
Overwrite color tables in /home/fulup/Workspace/Linux-Marine/resources/rules/color_tables
    [0] chartsymbols_dfo.xml
    [1] chartsymbols_S52.xml
    [2] chartsymbols_S57.xml
    [3] chartsymbols_French.xml
    [4] chartsymbols_SWE.xml
Select color definition: 3
Using color table chartsymbols_French.xml
/bin/sh: line 1: ./convert_colors_xml2csv.sh: No such file or directory
chartsymbols.xml not found at: /home/fulup/Workspace/Linux-Marine/SMAC-M/chartsymbols_S57.xml
Existing layers found in /home/fulup/Workspace/Linux-Marine/resources/rules/layer_rules
Traceback (most recent call last):
  File "/home/fulup/Workspace/Linux-Marine/SMAC-M/chart-installation/generate_map_files/generate_map_config.py", line 178, in <module>
    generate_basechart_config(data_path, map_path, rule_set_path,
  File "/home/fulup/Workspace/Linux-Marine/SMAC-M/chart-installation/generate_map_files/mapgen/basechart.py", line 103, in generate_basechart_config
    process_all_layers(data_path, map_path, rule_set_path, point_table,
  File "/home/fulup/Workspace/Linux-Marine/SMAC-M/chart-installation/generate_map_files/mapgen/basechart.py", line 164, in process_all_layers
    chartsymbols = ChartSymbols(

>>> ERROR
  File "/home/fulup/Workspace/Linux-Marine/SMAC-M/chart-installation/generate_map_files/mapgen/chartsymbols.py", line 60, in __init__

    raise Exception('chartsymbol file do not exists')
Exception: chartsymbol file do not exists

```

**Comment by MrBlenny** [comment]
I had the same problem. I have ignored the `LIGHTS` layer and then got the same issue with the chartsymbols.

After that, I got exactly the same error as you. I did a bunch of fiddling but I think what resolved this for me was just updating the path the `--chartsymbols` path when calling `generate_toml_config`.

I have a working example here:
https://github.com/Greenroom-Robotics/SMAC-M#greenroom-notes
