### ISSUE TITLE
Generating mapfiles does not work

### ISSUE THREAD

**Issue by VladimirKalachikhin** [LarsSchy/SMAC-M#33]
```
:~/SMAC-M$ python3 chart-installation/generate_map_files/generate_map_config.py ./s57/configfile.toml
Overwrite color tables in /home/stager/SMAC-M/resources/rules/color_tables
    [0] chartsymbols_SWE.xml
    [1] chartsymbols_S57.xml
    [2] chartsymbols_dfo.xml
    [3] chartsymbols_S52.xml
    [4] chartsymbols_French.xml
Select color definition: 1
Using color table chartsymbols_S57.xml
/bin/sh: 1: ./convert_colors_xml2csv.sh: not found
chartsymbols.xml not found at: /home/stager/SMAC-M/chartsymbols_S57.xml
Overwrite color tables in /home/stager/SMAC-M/resources/rules/layer_rules
Traceback (most recent call last):
  File "chart-installation/generate_map_files/generate_map_config.py", line 153, in <module>
    rule_set_path, "layer_rules"))
  File "/home/stager/SMAC-M/chart-installation/generate_map_files/utils/ruleutils.py", line 40, in create_layer_rules
    force_sub_dir(config_path, "layer_rules"))
  File "/home/stager/SMAC-M/chart-installation/generate_map_files/utils/dirutils.py", line 32, in copy_and_replace
    shutil.copytree(src, dst)
  File "/usr/lib/python3.6/shutil.py", line 315, in copytree
    names = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: '/home/stager/SMAC-M/chart-installation/generate_map_files/resources/layer_rules'
```

Any python app does rot after one year...

**Comment by jdsails** [comment]
If you manually copy layer_rules from the rules folder up one level to the resources folder, this error goes away. I expect the script could be modified to look in rules in the file path too.
